from aragon_bulk_budget_loader import AragonBulkBudgetLoader
from budget_loader import BudgetLoader
from simple_budget_loader import SimpleBudgetLoader
from glossary_loader import GlossaryLoader
from stat_loader import StatLoader
from entity_loader import EntityLoader
from payments_loader import PaymentsLoader